// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: metrics.sql

package db

import (
	"context"
	"database/sql"
)

const countCommunities = `-- name: CountCommunities :one
SELECT COUNT(DISTINCT community_id) FROM user_subreddit_activity WHERE community_id IS NOT NULL
`

func (q *Queries) CountCommunities(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCommunities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countGraphLinks = `-- name: CountGraphLinks :one
SELECT COUNT(*) FROM graph_links
`

func (q *Queries) CountGraphLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countGraphLinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countNodesByType = `-- name: CountNodesByType :one
SELECT COUNT(*) FROM graph_nodes WHERE type = $1
`

func (q *Queries) CountNodesByType(ctx context.Context, type_ sql.NullString) (int64, error) {
	row := q.db.QueryRowContext(ctx, countNodesByType, type_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getCrawlJobStats = `-- name: GetCrawlJobStats :one
SELECT 
    COUNT(*) FILTER (WHERE status = 'pending') as pending_jobs,
    COUNT(*) FILTER (WHERE status = 'processing') as processing_jobs,
    COUNT(*) FILTER (WHERE status = 'completed') as completed_jobs,
    COUNT(*) FILTER (WHERE status = 'failed') as failed_jobs
FROM crawl_jobs
`

type GetCrawlJobStatsRow struct {
	PendingJobs    int64
	ProcessingJobs int64
	CompletedJobs  int64
	FailedJobs     int64
}

func (q *Queries) GetCrawlJobStats(ctx context.Context) (GetCrawlJobStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getCrawlJobStats)
	var i GetCrawlJobStatsRow
	err := row.Scan(
		&i.PendingJobs,
		&i.ProcessingJobs,
		&i.CompletedJobs,
		&i.FailedJobs,
	)
	return i, err
}

const getDatabaseStats = `-- name: GetDatabaseStats :one
SELECT
    (SELECT COUNT(*) FROM subreddits) as subreddit_count,
    (SELECT COUNT(*) FROM users) as user_count,
    (SELECT COUNT(*) FROM posts) as post_count,
    (SELECT COUNT(*) FROM comments) as comment_count
`

type GetDatabaseStatsRow struct {
	SubredditCount int64
	UserCount      int64
	PostCount      int64
	CommentCount   int64
}

func (q *Queries) GetDatabaseStats(ctx context.Context) (GetDatabaseStatsRow, error) {
	row := q.db.QueryRowContext(ctx, getDatabaseStats)
	var i GetDatabaseStatsRow
	err := row.Scan(
		&i.SubredditCount,
		&i.UserCount,
		&i.PostCount,
		&i.CommentCount,
	)
	return i, err
}
