// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
)

type Comment struct {
	ID        string
	PostID    string
	Author    string
	Subreddit string
	ParentID  sql.NullString
	Body      sql.NullString
	CreatedAt sql.NullTime
	Score     sql.NullInt32
	LastSeen  sql.NullTime
	Depth     sql.NullInt32
}

type CrawlJob struct {
	ID          int32
	Subreddit   string
	Status      string
	Retries     sql.NullInt32
	LastAttempt sql.NullTime
	DurationMs  sql.NullInt32
	EnqueuedBy  sql.NullString
	CreatedAt   sql.NullTime
	UpdatedAt   sql.NullTime
}

type GraphLink struct {
	Source    string
	Target    string
	CreatedAt sql.NullTime
}

type GraphNode struct {
	ID        string
	Name      sql.NullString
	Val       sql.NullInt32
	Type      sql.NullString
	CreatedAt sql.NullTime
}

type Post struct {
	ID        string
	Subreddit string
	Author    string
	Title     sql.NullString
	Selftext  sql.NullString
	Permalink sql.NullString
	CreatedAt sql.NullTime
	Score     sql.NullInt32
	Flair     sql.NullString
	Url       sql.NullString
	IsSelf    sql.NullBool
	LastSeen  sql.NullTime
}

type Subreddit struct {
	Name        string
	Title       sql.NullString
	Description sql.NullString
	Subscribers sql.NullInt32
	CreatedAt   sql.NullTime
	LastSeen    sql.NullTime
}

type User struct {
	Username  string
	CreatedAt sql.NullTime
	LastSeen  sql.NullTime
	FirstSeen sql.NullTime
}
