// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scheduled_jobs.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createScheduledJob = `-- name: CreateScheduledJob :one
INSERT INTO scheduled_jobs (
    name, 
    description, 
    subreddit_id, 
    cron_expression, 
    enabled, 
    next_run_at, 
    priority,
    created_by
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, description, subreddit_id, cron_expression, enabled, last_run_at, next_run_at, priority, created_at, updated_at, created_by
`

type CreateScheduledJobParams struct {
	Name           string
	Description    sql.NullString
	SubredditID    sql.NullInt32
	CronExpression string
	Enabled        bool
	NextRunAt      time.Time
	Priority       sql.NullInt32
	CreatedBy      sql.NullString
}

func (q *Queries) CreateScheduledJob(ctx context.Context, arg CreateScheduledJobParams) (ScheduledJob, error) {
	row := q.db.QueryRowContext(ctx, createScheduledJob,
		arg.Name,
		arg.Description,
		arg.SubredditID,
		arg.CronExpression,
		arg.Enabled,
		arg.NextRunAt,
		arg.Priority,
		arg.CreatedBy,
	)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SubredditID,
		&i.CronExpression,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const deleteScheduledJob = `-- name: DeleteScheduledJob :exec
DELETE FROM scheduled_jobs WHERE id = $1
`

func (q *Queries) DeleteScheduledJob(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, deleteScheduledJob, id)
	return err
}

const getScheduledJob = `-- name: GetScheduledJob :one
SELECT id, name, description, subreddit_id, cron_expression, enabled, last_run_at, next_run_at, priority, created_at, updated_at, created_by
FROM scheduled_jobs
WHERE id = $1
`

func (q *Queries) GetScheduledJob(ctx context.Context, id int32) (ScheduledJob, error) {
	row := q.db.QueryRowContext(ctx, getScheduledJob, id)
	var i ScheduledJob
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.SubredditID,
		&i.CronExpression,
		&i.Enabled,
		&i.LastRunAt,
		&i.NextRunAt,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const listDueScheduledJobs = `-- name: ListDueScheduledJobs :many
SELECT id, name, description, subreddit_id, cron_expression, enabled, last_run_at, next_run_at, priority, created_at, updated_at, created_by
FROM scheduled_jobs
WHERE enabled = true AND next_run_at <= now()
ORDER BY priority DESC, next_run_at ASC
`

func (q *Queries) ListDueScheduledJobs(ctx context.Context) ([]ScheduledJob, error) {
	rows, err := q.db.QueryContext(ctx, listDueScheduledJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledJob
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SubredditID,
			&i.CronExpression,
			&i.Enabled,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledJobs = `-- name: ListScheduledJobs :many
SELECT id, name, description, subreddit_id, cron_expression, enabled, last_run_at, next_run_at, priority, created_at, updated_at, created_by
FROM scheduled_jobs
ORDER BY next_run_at ASC
LIMIT $1::int OFFSET $2::int
`

type ListScheduledJobsParams struct {
	Column1 int32
	Column2 int32
}

func (q *Queries) ListScheduledJobs(ctx context.Context, arg ListScheduledJobsParams) ([]ScheduledJob, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledJobs, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledJob
	for rows.Next() {
		var i ScheduledJob
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.SubredditID,
			&i.CronExpression,
			&i.Enabled,
			&i.LastRunAt,
			&i.NextRunAt,
			&i.Priority,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleScheduledJob = `-- name: ToggleScheduledJob :exec
UPDATE scheduled_jobs
SET enabled = $2,
    updated_at = now()
WHERE id = $1
`

type ToggleScheduledJobParams struct {
	ID      int32
	Enabled bool
}

func (q *Queries) ToggleScheduledJob(ctx context.Context, arg ToggleScheduledJobParams) error {
	_, err := q.db.ExecContext(ctx, toggleScheduledJob, arg.ID, arg.Enabled)
	return err
}

const updateScheduledJob = `-- name: UpdateScheduledJob :exec
UPDATE scheduled_jobs
SET name = $2,
    description = $3,
    cron_expression = $4,
    enabled = $5,
    next_run_at = $6,
    priority = $7,
    updated_at = now()
WHERE id = $1
`

type UpdateScheduledJobParams struct {
	ID             int32
	Name           string
	Description    sql.NullString
	CronExpression string
	Enabled        bool
	NextRunAt      time.Time
	Priority       sql.NullInt32
}

func (q *Queries) UpdateScheduledJob(ctx context.Context, arg UpdateScheduledJobParams) error {
	_, err := q.db.ExecContext(ctx, updateScheduledJob,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.CronExpression,
		arg.Enabled,
		arg.NextRunAt,
		arg.Priority,
	)
	return err
}

const updateScheduledJobLastRun = `-- name: UpdateScheduledJobLastRun :exec
UPDATE scheduled_jobs
SET last_run_at = $2,
    next_run_at = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateScheduledJobLastRunParams struct {
	ID        int32
	LastRunAt sql.NullTime
	NextRunAt time.Time
}

func (q *Queries) UpdateScheduledJobLastRun(ctx context.Context, arg UpdateScheduledJobLastRunParams) error {
	_, err := q.db.ExecContext(ctx, updateScheduledJobLastRun, arg.ID, arg.LastRunAt, arg.NextRunAt)
	return err
}
