// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"
)

const getUser = `-- name: GetUser :one
SELECT username, created_at, last_seen, first_seen FROM users WHERE username = $1
`

func (q *Queries) GetUser(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, username)
	var i User
	err := row.Scan(
		&i.Username,
		&i.CreatedAt,
		&i.LastSeen,
		&i.FirstSeen,
	)
	return i, err
}

const getUserSubreddits = `-- name: GetUserSubreddits :many
SELECT DISTINCT posts.subreddit FROM posts WHERE posts.author = $1
UNION
SELECT DISTINCT comments.subreddit FROM comments WHERE comments.author = $1
`

func (q *Queries) GetUserSubreddits(ctx context.Context, author string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getUserSubreddits, author)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var subreddit string
		if err := rows.Scan(&subreddit); err != nil {
			return nil, err
		}
		items = append(items, subreddit)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT username, created_at, last_seen, first_seen FROM users ORDER BY last_seen DESC LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.Username,
			&i.CreatedAt,
			&i.LastSeen,
			&i.FirstSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (username, first_seen, last_seen)
VALUES ($1, now(), now())
ON CONFLICT (username) DO UPDATE SET last_seen = now()
`

func (q *Queries) UpsertUser(ctx context.Context, username string) error {
	_, err := q.db.ExecContext(ctx, upsertUser, username)
	return err
}
